### ISSUE TITLE
Giga Internet (RS)

### ISSUE THREAD

**Issue by RodrigoHahn** [InternetSemLimites/InternetSemLimites#12]
Opa,

A Giga Internet (Porto Alegre - RS) não vai adotar a limitação de tráfego.
Referências:
- http://giga.com.br/
- http://exame.abril.com.br/negocios/dino/noticias/provedora-de-internet-apresenta-alternativa-com-planos-ilimitados-frente-a-novas-franquias-de-banda-larga.shtml

Parabéns pelo ótimo trabalho.

**Comment by fbraz3** [comment]
Já fiz um pull request com a info =)

**Comment by jlcarvalho** [comment]
Valeu ;)
