### ISSUE TITLE
Problema com a fonte da Algar Telecom

### ISSUE THREAD

**Issue by jlcarvalho** [InternetSemLimites/InternetSemLimites#16]
No caso da Algar Telecom a fonte confere, porém eu não consegui adicioná-la via https://archive.is/, logo, coloquei o link direto, mas o ideal seria encontrar uma alternativa.

**Comment by anewuser** [comment]
As duas versões (_desktop _e móvel) da página foram salvas corretamente:

https://archive.is/Lzgc0

https://archive.is/3a5Yy

**Comment by cuducos** [comment]
Corrigido!
