### ISSUE TITLE
Site & Logo: Internet Sem Limites

### ISSUE THREAD

**Issue by kazzkiq** [InternetSemLimites/InternetSemLimites#17]
#### Esta Issue é apenas para propostas relacionadas a parte visual (UI e logotipo).

---

Acho que seria interessante ter algum logotipo para a iniciativa, principalmente no caso da criação e uma SPA (como descrito na discussão #9).

Eu bolei algo simples mas que passa o objetivo da iniciativa, que é o de manter o uso da internet de forma ilimitada:

![internetsemlimitess](https://cloud.githubusercontent.com/assets/1953194/14515332/7c7cec2a-01cf-11e6-92f3-4e0215855e3c.png)

O que vocês acham da ideia?

Obs.: Outras propostas de logo também são bem vindas.

**Comment by jlcarvalho** [comment]
Pô, eu curti mano. Valeu pela contribuição. Vamos adotar ele.

A gente tá pensando em criar um site baseado na API que o CMS que o @cuducos criou, pra facilitar a busca de provedores pelas pessoas que não tem intimidade com o Github.

Acha que consegue ajudar a gente nisso também? Eu não manjo muito de design.

**Comment by pedrobastosdz** [comment]
Curti o logo!
Tô dentro pra criar o site.
Topa @kazzkiq ?

**Comment by kazzkiq** [comment]
Opa, bacana que a galera curtiu.

@pedrobastosdz Topo demais! Só que na outra discussão (#9) o @sunw4r comentou que ia montar um layout, então acho que seria interessante alinharmos quem ficaria responsável pra não rolar retrabalho.

Aliás, @jlcarvalho, atualmente estamos com 3 issues discutindo a questão do site, seria interessante centralizarmos toda a discussão em apenas uma, não? Como a #9 é a mais antiga, poderia ficar por lá mesmo, o que você acha?

Quanto ao logo, caso vocês estejam de acordo com a minha proposta eu já fecho a issue e compartilho o arquivo fonte (vetorizado).

**Comment by jlcarvalho** [comment]
@kazzkiq tem muita coisa rolando na #9, melhor manter aqui mesmo e só atualizar o título da issue.

**Comment by sunw4r** [comment]
@kazzkiq pode mandar bala e assumir o layout! Meu tempo tá extremamente escasso nas últimas semanas e eu não contava com a celeridade que o pessoal ia tocar a API! ahaha! :-)
[ ]s

**Comment by kazzkiq** [comment]
@jlcarvalho Beleza, atualizei o título e editei a primeira postagem com um _disclaimer_.

**A ideia seria centralizar todas as questões de design nesta issue.**

@sunw4r Tranquilo, eu tbm me impressionei com a velocidade dos devs, haha! @pedrobastosdz Eu também estou meio corrido com o trabalho e não devo conseguir ajudar com a layout, você acha que consegue bolar uma proposta pra gente?

**Comment by cuducos** [comment]
@kazzkiq @sunw4r Não quero me envolver com o front-end. Mas se precisarem de alguma ajuda para a integração (da API no front-end; ou, se por ventura quiserem botar o site dentro da aplicação da API), contem comigo pra ajudar nessa integração ; )

**Comment by kazzkiq** [comment]
@cuducos Show de bola! Como a API já expõe os dados em JSON, a integração deve ser bem tranquila. Apenas uma coisa, geralmente os browsers não permitem uma requisição AJAX para outro domínio (CORS) sem o header `Access-Control-Allow-Origin` por questões de segurança, então seria interessante adicionar ele lá também.

[Mais informações sobre isso aqui](http://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work)

**Comment by cuducos** [comment]
@kazzkiq Tranquilo! Vão me informando as tecnologias que vão usar (não, não precisa usar relatórios haha; só façam isso num _repo_ público e eu stalkeio hehe) e aí integramos o front como back numa boa… Só digo isso pois assim já preparo o server para gerar o que precisar (SASS para CSS, por exemplo) dinamicamente ; )

**Comment by pedrobastosdz** [comment]
@kazzkiq Topo de boa. Vou fazer um wireframe pra validar a estrutura aqui com vcs.

**Comment by pedrobastosdz** [comment]
![mobile - selecione estado](https://cloud.githubusercontent.com/assets/18469334/14549128/6cd84f0c-0293-11e6-96ab-fc972b1a7493.png)

![mobile - lista de operadoras](https://cloud.githubusercontent.com/assets/18469334/14549127/6cd2c406-0293-11e6-8250-3300e795fd26.png)

**Comment by pedrobastosdz** [comment]
![web](https://cloud.githubusercontent.com/assets/18469334/14549147/ac26b608-0293-11e6-80d0-1548071c9f80.png)

**Comment by pedrobastosdz** [comment]
Bem, era isso q eu tinha em mente. Listar primeiro os provedores pra depois aparecer o botão para adicionar provedor. 
Na versão web seria o mapa do Brasil, a pessoa seleciona o estado e já exibe do lado. É uma forma mais rápida de pesquisa e além disso podemos deixar aqueles estados q não tem provedor cadastrado, com outra cor, (cinza por exemplo).

**Comment by kazzkiq** [comment]
@pedrobastosdz Eu curti a estrutura! Achei que ficou simples, direto e bem informativo. Essa ideia do mapa do Brasil é ótima pra filtrar por estado, bem mais chamativa que apenas um dropdown ou campo de texto. E o fato do site estar simples facilita também na questão de responsividade.

Pra mim a estrutura está ótima.

O que o resto da galera acha?

cc @jlcarvalho

**Comment by cuducos** [comment]
Hey ho!

**Comment by leomeloxp** [comment]
@kazzkiq Seria possível disponibilizar um brand guidelines ou colour pallet? (não conheço os termos em Pt-BR). Queria ter a certeza que estamos usando as cores certas no site .github.io.

**Comment by cardosoedgar** [comment]
@kazzkiq Pegando o embalo do @leomeloxp, se der pra disponibilizar a logo em .png bonitinha e em alta resolução seria massa também.

**Comment by igorvieira** [comment]
Que trabalho incrível jovens, precisando algum dev front, eu estarei a disposição.

**Comment by kazzkiq** [comment]
@leomeloxp A parte de design está com o @pedrobastosdz, acho que o ideal seria esperarmos alguma proposta de design dele (em cima desses wireframes) pra batermos o martelo nas cores (aquele azul de fundo do logo foi mais um exemplo de aplicação feito na correria mesmo haha)

#### Link para o logotipo: **[DROPBOX](https://www.dropbox.com/sh/0gw4xfosw94cg66/AAB-SDV_unFF0lS2J9ok4EJea?dl=0)**

(.AI, .EPS, .SVG, .PNG)

Salvei em vários formatos porque não sei qual editor a galera usa, assim a gente tem certeza que pelo menos um deles funciona.

Inicialmente eu joguei no Dropbox, mas a gente pode criar um outro repo pra deixar todos os fontes relacionados à design também. Vocês que mandam.

**Comment by leomeloxp** [comment]
@IgorVieira Se quiser, dá uma olhada em #19 e no repo pro .github.io, eu comecei um site usando Jekyll.

@kazzkiq Firmeza, imagino que vá sair aqui as propostas de designs, vou estar no aguardo. Eu tenho umas coisas pra adicionar em termos de front antes de precisar finalizar o design por isso acho que vai tudo se acertar mais ou menos no mesmo tempo. Valeu pelos logos 👍

**Comment by pedrobastosdz** [comment]
Galera, desculpa a demora.
Vejam minha ideia pra interface: https://goo.gl/oISv0M

Deem seus feedbacks pra gente ir alinhando.

**Comment by fbraz3** [comment]
Bah muito bonito o layout kra! =)

Minha única sugestão seria um menu de navegação, pros usuários preguiçosos
não fugirem da pagina por não saberem que tem que dar scroll down.

2016-04-15 22:21 GMT-03:00 Pedro Bastos notifications@github.com:

**Comment by kazzkiq** [comment]
@pedrobastosdz Eu também curti muito o layout!

Algumas sugestões:
- Aumentar um pouco o logo
- Diminuir um pouco o tamanho da hashtag
- Aumentar um pouco o texto em baixo da hashtag
- **Proposta:** Adicionar seção "O que você pode fazer?" abaixo das operadoras malvadas ([mais informações sobre isso no Gitter](https://gitter.im/InternetSemLimites/InternetSemLimites))

Fora isso, ta super bacana!

Vamos esperar o feedback do resto da galera e aí já podemos ir passando toda essa estrutura visual pro front-end. cc @leomeloxp

**Comment by felipe-prenholato** [comment]
Não deixem de fazer um HTML legível para cegos (e outras pessoas com
deficiência). Nesse caso provavelmente teríamos uma navegação (ou lista
mesmo) oculta visualmente mas legível pelo leitor de tela.

acessibilidadelegal.com e https://www.w3.org/WAI/tutorials/menus/structure/
sao bons recursos.

PS: mto boa a separacao céu / inferno.

**Comment by leomeloxp** [comment]
@pedrobastosdz Comecei a implementar seu design.
@kazzkiq A sua proposta é muito boa (como eu disse no gitter), mas acho que faria mais sentido ela ficar **entre** o _céu_ e o _inferno_, visto que é exatamente o que as pessoas entre os dois devem/podem fazer (e talvez fique melhor no layout também 😜 ).
Talvez seja a hora de fecharmos essa issue e para cada sugestão abrir uma issue no repo do site.
Além do mais, qualquer coisa que exija discussão talvez seja melhor abordada no gitter, para evitar tornar essas issues um bate-papo. Minha sugestão seria abrir uma issue no repo do site para coisas como o tamanho do logo. Depois, quando alguém implementar a solução fazemos PR e fechamos a issue.

**EDIT**: @chronossc obrigado por lembrar da accessibilidade, é um fator muito importante para o projeto e vou me preocupar em implementar suporte para aria. Talvez se tivéssemos alguém para testar (ou me ensinar a testar localmente), ajudaria.

**Comment by leomeloxp** [comment]
Pessoal, versão inicial do site está aqui: http://leomeloxp.net/InternetSemLimites.github.io/ Não tem muito ainda mas foi o que deu pra fazer numa manhã 😄 Quem quiser me ajudar, entra no gitter, cria issues no repositório e/ou faz fork do meu leomeloxp/InternetSemLimites.github.io no branch develop (que é onde está o código).

Vou colocar um readme lá para que saibam como contribuir para o código. Os próximos passos agora são:
- [ ] implementar o JS da API.
- [ ] terminar a parte de estilos, criar os detalhes das núvens, ícones, etc (vamos ter animações marotas em scroll down ou nem?).
- [ ] implementar suporte a acessibilidade.
- [ ] conseguir com que as operadoras mudem de idea _para que o Brasil possa levar a zueira onde nenhum homem jamais esteve._

**Comment by jlcarvalho** [comment]
Eu acho que tinha que dar menos destaque pras logos das que vão limitar,
mas no mais está sensacional.

Em sáb, 16 de abr de 2016 10:42, Leonardo Melo notifications@github.com
escreveu:

**Comment by leomeloxp** [comment]
@pedrobastosdz Cara, preciso de umas informações sobre o seu design para poder terminar o site. Se puder me mandar:
- Fonte utilizada
- HEX das Cores (eg, Azul, Verde, cinzas, marrom, vermelho e amarelo)
- SVG das nuvens e da transição para o inferno.
- Qualquer outra coisa que possa ser importante e eu me esqueci XD

Valeu o/

PS: se tiver um arquivo .sketch to site, pode mandar esse também que eu dou um jeito de extrair os resources aqui.

**Comment by pedrobastosdz** [comment]
@leomeloxp Pra deixar tudo na mão, tô enviado o psd do site e os svg: https://goo.gl/qoHRDV

Se quiser colocar um parallax nas duas camadas das nuvens e nas estalactites acredito q ficaria mais legal. Ex.: http://gardenestudio.com.br

Sobre a section "O que você pode fazer?" concordo com o @kazzkiq, é melhor que fique abaixo das operadoras com Limite pelo fluxo de leitura do site.

**Comment by leomeloxp** [comment]
@pedrobastosdz Valeu, amanhã dou uma olhada nos resources e tento colocar o parallax também. Hoje consegui botar o JS. Tá na minha versão de teste aqui: http://leomeloxp.net/InternetSemLimites.github.io/

Sobre o _O que você pode fazer?_ talvez faça mesmo sentido colocar depois do hall of shame. Será que alguém poderia me dar o conteúdo para que eu crie a secção? Como não moro no Brasil e não acompanho tantas notícias não sei exatamente quais seriam os modos que alguém pode ajudar.
