### ISSUE TITLE
Catálogo em JSON

### ISSUE THREAD

**Issue by vinaocruz** [InternetSemLimites/InternetSemLimites#18]
Como sugestão, que tal criar um catálogo dessa empresas em json? Fizemos algo na comunidade phpba (https://github.com/phpba/php-business-ba)

Outra sugestão é usar o github.io para criar o site e já consumir o json para facilitar aos usuários.

**Comment by jlcarvalho** [comment]
Opa, o @cuducos já criou como visto na issue #9, tem até um CMSzinho pra facilitar.

**Comment by vinaocruz** [comment]
Acabei de ver, o issues estava como fechado. Muito bom!

**Comment by jlcarvalho** [comment]
Então vou fechar esse aqui ;)
