### ISSUE TITLE
Criar um github pages, para pessoas que não usam Github

### ISSUE THREAD

**Issue by leomeloxp** [InternetSemLimites/InternetSemLimites#19]
Talvez pudesse ser útil criar um Github Pages para transformar esses arquivos markdown em algo mais acessível para usuários comuns: https://pages.github.com/

Uma boa implementação seria criar uma organição chamada InternetSemLimites e criar a página lá, para que tenhamos InternetSemLimites.github.io

**Comment by phouverneyuff** [comment]
+1

**Comment by cuducos** [comment]
A gente já discute algo assim no Issue #9, cai pra lá : )

Resumo:
- tem gente planejando fazer algo assim já, caí pra lá e juntem as forças : ) Tem até proposta de logo (Issue #17) já!
- botei [uma API no ar para servir os dados](http://github.com/cuducos/InternetSemLimitesCMS) para um futuro SPA (single page application; mas isso não tenho como fazer agora).

**Comment by neysimoes** [comment]
Precisamos mover o repo para uma org, assim poderemos ter o domínio internetsemlimites.github.io (issue #21)

**Comment by jlcarvalho** [comment]
@neysimoes já movi pra uma organização.

**Comment by wagnerbeethoven** [comment]
melhor pra colocar como github page, muito mais fácil de atualizar.

**Comment by jlcarvalho** [comment]
Certo, eu e o @cuducos acabamos optando por criar uma API externa ontem pra facilitar o cadastro dos provedores, já que aqui no `README.md` tava ficando bem redundante.

Então agora temos que criar um site que consuma essa API para colocarmos no GH Pages.

O que vai acabar resultando na depreciação do `README.md`, tendo em vista que vai ficar complicado ficar atualizando ele e a API (que é gerenciada por um CMS usando Django).

**Comment by cuducos** [comment]
Por enquanto estou me esforçando para passar para a API todo _commit_ que vejo aqui. Está de boa.

Acabei de colocar no ar um [formulário para envio de provedores](http://internetsemlimites.herokuapp.com/new/) direto para o CMS da API (fica pendente _moderação_ para a gente dar uma verificada na fonte, passar pro archive.is se for o caso etc).

> (O código do front-end formulário é umas das coisas mais porcas que fiz na vida, pois acho que quando esse site existir esse formulário podia mudar para lá, ou, pelo menos, eu poderia aproveitar a identidade visual e replicar.)

**Comment by leomeloxp** [comment]
Legal o logo em #17 . Muito bom o pessoal se candidatando e ajudando no que pode também. 

Vejo que a issue #17 é bem focada em Design e também já existe uma focada na API #9 pro projeto. Talvez pudéssemos utilizar essa daqui para o Desenvolvimento do Front-end, assim dá pra dividir bem as prioridades e cada um bote focar e contribuir na área que sentir mais a vontade ou eficaz.

Como já existe uma API de backend pro site acho que seria bem simples de criar um front-end usando gh-pages e provavelmente Jekyll (visto que o Github integra legal com o Jekyll). Se quiserem também eu escrevi um gerador de site estático que integra com gh-pages que estou usando pro meu site. O código não está aberto ainda porque preciso limpar umas partes.

Também posso ajudar com React e talvez Angular (pouco) se o pessoal preferir. O que vocês acham?

Além do mais podemos também usar o gitter.im para mensagens instantâneas.

Por favor opinem em qual metodologia utilizar para o front e já podemos começar a construir. Eu moro no Reino Unido e com isso meu fuso é +4 horas em relação ao Brasil no momento. FDS é de boas para contribuir aqui e depois do trabalho também.

Sugestões para o front até o momento incluem:
- Plataforma:
  - [Jekyll](https://jekyllrb.com/docs/github-pages/)
  - [Gerador Estático](https://www.staticgen.com/) (Gulp, ou outros, preferência pessoal por JS)
- CSS: SASS (compilado pelo Jekyll ou Gulp/JS)
- Javascript:
  - ES2015/16, se possível/necessário
  - React
  - Angular
  - jQuery
- Framework:
  - [Foundation 6](http://foundation.zurb.com/sites/docs/)
  - Bootstrap (3 ou 4, se quiserem Flexbox)

Não usaríamos tudo acima, mas esses são os que eu prefiriria e poderia ajudar de modo mais eficiente, feedback é sempre bem vindo.

**Comment by jlcarvalho** [comment]
Boa @leomeloxp. Concordo com tudo que falou, acho que rola criar um gitter.im pra isso aqui não virar bate papo mesmo.

Quanto as tecnologias a serem utilizadas, particularmente sou bem produtivo com o Angular, mas como acredito que o site vai ser algo bem simples, só o Jekyll já resolveria, inclusive nem precisamos de frameworks js e css.

**Comment by cuducos** [comment]
@leomeloxp Apenas lembrando de uma complexidade que o @kazzkiq mencionou [em outro tópico](https://github.com/InternetSemLimites/InternetSemLimites/issues/17#issuecomment-210119249):

> Como a API já expõe os dados em JSON, a integração deve ser bem tranquila. Apenas uma coisa, geralmente os browsers não permitem uma requisição AJAX para outro domínio (CORS) sem o header Access-Control-Allow-Origin por questões de segurança, então seria interessante adicionar ele lá também.

Não sou expert no front-end. O esse comentário me fez ver que ao fazer o CMS/API em Python e Django, talvez acabei — sem querer, claro —  limitando um pouco as opções para o front-end. 

Na arquitetura que você pensou, isso seria um problema? A página estática (gerada pelo Jekyll) carregaria o JSON (via browser, com JavaScript) de outro servidor sem problemas?

Digo isso pois, caso contrário, temos que ver se alinhamos tudo para:
1. ou rodar o site em paralelo no mesmo Heroku que está a API;
2. ou refazemos a API em outro servidor, plataforma, framework ou linguagem;
3. fazermos o site não ser estático e carregamos a API _server-side_ (aí com total liberdade de servidor, plataforma, linguagem e framework).

**Comment by jlcarvalho** [comment]
@cuducos liberar o CORS no Django deve ser bem de boa e não acho que você limitou as possibilidades do front não.

**Comment by kazzkiq** [comment]
@cuducos Acho que a API está perfeita da forma que está sendo montada, pra habilitar CORS basta apenas adicionar um header `Access-Control-Allow-Origin: *` no response das APIs.

Não manjo absolutamente nada de Python, mas um exemplo em Node.js seria algo como:

``` js
app.get('/hall-of-shame', function(req, res) { 
    //... adiciona cabeçalho
    res.header("Access-Control-Allow-Origin", "*");

    // retorna o response
    res.send(jsonComDadosDoBanco);
});
```

Sobre onde rodar o site, existe a possibilidade de usar o gh-pages com o **[RawGit](https://rawgit.com/)** servindo de CDN dos resources. Isso significaria que todo o front-end não consumiria nenhum recurso do Heroku, além da API em si obviamente.

Separando as duas partes, eu acho que a aplicação se torna mais escalável, principalmente no nosso caso, já que estamos usando serviços gratuitos. Então quanto menos _overhead_ em um serviço, melhor.

Então recapitulando, minha sugestão:
- **Heroku**: Responsável pela API/Persistência de dados;
- **GH-pages:** Responsável por expor a página (front-end);
- **RawGit:** Responsável por gerar versões em cache dos recursos front-end (CSS, JS, imagens).

Todos os serviços são gratuitos e acho que usando os três conseguiríamos ter uma boa escalabilidade sem nenhum custo. O que acham?

**Comment by cuducos** [comment]
Se só com CORS resolve, tá lindo! Amanhã implemento : )

**Comment by felipe-prenholato** [comment]
Tem um pacote, django-cors, use ele.

**Comment by leomeloxp** [comment]
Se alguém puder me adicionar a equipe então pr'eu começar a criar o gh-pages e gitter.im. Imagino que os wireframes em #17 sejam para essa gh-pages, caso não seja, imagino que será bem parecido de qualquer modo.

Assim que eu criar a base do Jekyll para o front vou desenvolver o código num fork e fazer PR (para que todos que queiram colaborar possam fazer seus próprios PRs). Num tenho muita experiência com PR no Github mas vai ser legal poder aprender =P

Se alguém mais quiser liderar o front, sintam-se a vontade, eu vou fazer aquilo que posso, quanto mais ajuda melhor!

**Comment by cuducos** [comment]
@leomeloxp Feito! Criei o repo .github.io também, e coloquei o @kazzkiq lá tb. É isso?

**Comment by cuducos** [comment]
CORS implementado ; )

``` console
$ curl -I -H "Origin: http://xp.to" internetsemlimites.herokuapp.com
HTTP/1.1 200 OK
Connection: keep-alive
Server: gunicorn/19.4.5
Date: Fri, 15 Apr 2016 11:13:43 GMT
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Content-Type: application/json
X-Frame-Options: SAMEORIGIN
Via: 1.1 vegur
```

**Comment by leomeloxp** [comment]
Okay, gitter criado: https://gitter.im/InternetSemLimites/InternetSemLimites

Vou começar no .github.io hoje na hora do almoço ou depois do trabalho.

**Comment by leomeloxp** [comment]
Update: Instalação inicial do Jekyll está num [fork meu aqui](https://github.com/leomeloxp/InternetSemLimites.github.io/tree/develop), o motivo pelo qual estou utilizando develop é porque uso Gitflow (com Sourcetree) e tudo que for pro master e voltar pro ISL.github.io vai virar o site.

Quem quiser ajudar pode fazer um fork e começar a editar. Eu vou tentar fazer o wireframe base hoje a noite, depois vou passar para integrar as APIs no front. 

Como o número de tarefas agora pode aumentar, talvez devêssemos fechar essa issue aqui e abrir issues individuais no outro repositório para cada tarefa que deva ser feita. O que acham?

Também tem uma sala no Gitter só para o site .io caso queiram discutir assuntos específicos. No mais é isso aí. Se alguém quiser contribuir e precisar de ajuda com Jekyll manda mensagem no gitter (ou outra rede social, ou abre issue no outro repo) e eu tento ajudar no que puder.

**Comment by cuducos** [comment]
Apoiado!

**Comment by ericoporto** [comment]
Adiciona o endereço da página no perfil do github do InternetSemLimites

**Comment by cuducos** [comment]
Boa, @ericoporto! Feito ; )
