### ISSUE TITLE
Mover repositório para uma organização

### ISSUE THREAD

**Issue by neysimoes** [InternetSemLimites/InternetSemLimites#21]
Voto por movermos o repositório para uma organização dentro do GitHub. Onde criaremos o GH pages da InternetSemLimites e poderemos centralizar tudo que fizermos (API, Site, discussões...).

Acredito que o próprio @jlcarvalho poderia ser dono junto com outros colaboradores, para aceitar PRs e moderar.

**Comment by jlcarvalho** [comment]
Pronto, movi pra uma organização e coloquei o @cuducos como colaborador, conforme mais pessoas forem contribuindo eu vou colocando como colaboradores.

Minha dúvida é: e quem tentar acessar o link antigo?

**Comment by jlcarvalho** [comment]
Ou melhor, já vi que o GH redireciona sozinho pra cá.

**Comment by cuducos** [comment]
Boa!
Já [passei a API para lá](https://github.com/InternetSemLimites/PublicAPI) : )
