### ISSUE TITLE
Site para pesquisas de operadoras SCM e algumas operadoras para adicionar

### ISSUE THREAD

**Issue by douglasanpa** [InternetSemLimites/InternetSemLimites#25]
Pessoal, para facilitar encontrar operadoras seria bom disponibilizar o site de buscas de operadoras SCM para o povo entrar em contato e verificar se terão franquia.

Esse é o site: http://goo.gl/ooYUil

Aproveitando, entrei em contato com algumas operadoras de Guarulhos/SP, me informaram por telefone que não terão franquias

iVeloz;
Red Fox Telecom;
Imunidade Digital;
WiNet;
W2i Telecom.

Algumas é mais Forte na cidade de São Paulo, outras em Itaquaquecetuba, em Guarulhos infelizmente elas atendem somente alguns bairros.

**Comment by jlcarvalho** [comment]
@douglasanpa , estamos evitando adicionar provedores que não expressem publicamente que não irão limitar o tráfego de dados.

**Comment by douglasanpa** [comment]
@jlcarvalho eu entendo... mas e o site de busca acho bom colocar no readme.

**Comment by jlcarvalho** [comment]
Eu acho show, vou colocar aqui.

**Comment by jlcarvalho** [comment]
@douglasanpa você sabe qual tipo de serviço o usuário tem que selecionar pra fazer a busca nesse site?

**Comment by douglasanpa** [comment]
@jlcarvalho Serviço de Comunicação Multimídia - 045

**Comment by douglasanpa** [comment]
Sobre as operadoras que achei a informação de ilimitado no site deles

iVeloz - o site informa ser ilimitado ( http://www.iveloz.net.br/ )
RedFox Telecom - Tambem é ilimitado ( http://redfoxtelecom.com.br/site/ )
imunidade digital - Sem franquia ( http://www.imunidadedigital.com.br/servicos.html#fibravalores )

**Comment by douglasanpa** [comment]
@jlcarvalho Peguei uma URL para já preenche o campo tipo de serviço com o serviço correto http://goo.gl/KQ465X

**Comment by fbraz3** [comment]
Acho que seria interessante não usar como fonte o site dos próprios provedores (que eles podem mudar a belprazer) e sim divulgações em mídia, pois fica mais fácil cobrar deles depois

**Comment by jlcarvalho** [comment]
@douglasanpa e @fbraz3, até o momento não estamos usando somente os sites como fonte (pelo menos não nos PR que aceitamos). Estamos usando o archive.is nas declarações públicas de cada provedor (então provedores que comunicaram via telefone também não entram na lista).

**Comment by KlusterX** [comment]
Olá a todos, 
Gostaria de deixar registrado o compromisso de que a Imunidade Digital não trabalha com franquias e **não** tem a intenção de incluir em planos convencionais, havendo sim a possibilidade de ser feito em casos destintos, pois pretendemos criar pontos wi-fi grátis em diversos pontos da cidade de Guarulhos e São Paulo.
Gostaria de informar que a partir deste mês estamos incluindo novos planos e valores, quais terão as informações no site a partir de 08/10 entre outras novidades.
E deixar a correção para o acesso as informações de nossos serviços, pois, o que o colega Douglas incluiu estão quebrados devido a atualizações em nosso website.
Desde já agradeço a atenção de todos.

http://www.imunidadedigital.com.br/servicos/fibra/index.html

http://www.imunidadedigital.com.br/servicos/radio/index.html

Henrique Lemos Ribeiro

**Comment by fbraz3** [comment]
@KlusterX existe algum comunicado oficial em mídias (site de noticias, redes sociais, etc)? 
Pergunto isso pois esse é um dos requisitos para participação da lista de provedores.
Outro ponto importante é que o contrato de prestação de serviços não pode citar coisas como "franquia promocionalmente ilimitada" ou similares.

**Comment by KlusterX** [comment]
fbraz3
Segue conforme solicitado:

https://www.facebook.com/imunidadedigital/

Abraço

**Comment by cuducos** [comment]
@KlusterX Muito obrigado, meu caro!

Você pode submeter os detalhes do teu serviço pelo [nosso formulário](https://internetsemlimites.herokuapp.com/new/) ? Use esse link aqui no campo **URL da fonte da informação**, por favor: `https://archive.is/svyp3`.
