### ISSUE TITLE
Automatizar update do `HALL_OF_SHAME.md` pela API

### ISSUE THREAD

**Issue by cuducos** [InternetSemLimites/InternetSemLimites#26]
@fbraz3 Quando eu fizer a API disso tu implemente? Tks

**Comment by fbraz3** [comment]
sem problemas, reaproveito 90% daquele script =)

**Comment by cuducos** [comment]
Feito: http://internetsemlimites.herokuapp.com/HALL_OF_SHAME.md

Hoje quero reorganizar o app, pq tá ficando uma bagunça. Devo mudar as URLs.

Tô pensando em fazer `/api/…` só para a API, `/md/…` só para esses MarkDowns, e `/new/` só para o formulário. Preciso sincronizar essa mudança contigo, pro `curl` não pegar `404` e sobrescrever no repo principal… quando é de boa pra ti?

**Comment by fbraz3** [comment]
Eu sobrescrevo só quando o tamanho do arquivo é maior que 1KB, acredito que um retorno 404 não tenha isso, mas posso pensar em implementar algo com o status no sh sem problemas.
De repente o melhor pra sincar essa mudança seria usar algum mensageiro instantâneo, mas pra mim o melhor horario é la pelo final da tarde quando ta mais tranquilo aqui no trampo =P

**Comment by cuducos** [comment]
De boa então : ) Te aviso quando mudar! Mto obrigado, @fbraz3

**Comment by fbraz3** [comment]
@cuducos mudei o sh pra pasta contrib do projeto da api e ja agendei a mudança do hall of shame =)

> 0 \* \* \* \* /home/automacao/InternetSemLimites/api/contrib/sync.sh > /home/automacao/logs/internetsemlimites.log
> 1 \* \* \* \* /home/automacao/InternetSemLimites/api/contrib/sync.sh shame > /home/automacao/logs/internetsemlimites.shame.log

**Comment by fbraz3** [comment]
Aproveitando, testei aqui o 404 do heroku e tem 318 B, então não é pra sobescrever mesmo

**Comment by cuducos** [comment]
Boa! Funcionando, podemos fechar essa _Issue_ né? Só não fechei pq como tu reabriu talvez tenha algo que eu não tenha visto…

**Comment by fbraz3** [comment]
tu ia mudar pra pasta md, por isso reabri. Ou de repente criamos outra issue pra isso.

**Comment by cuducos** [comment]
Boa. Passei o issue pro outro repo: https://github.com/InternetSemLimites/PublicAPI/issues/2
