### ISSUE TITLE
No English description of repository

### ISSUE THREAD

**Issue by vi** [InternetSemLimites/InternetSemLimites#28]
This repository appears on [trending repositories](https://github.com/trending) page, yet I can't describe what is it about even by visiting the page.

There is some list of sites, some "hall of shame", but that is all.

I think all popular repositories should provide some short English description in addition to localized description.

**Comment by robsonsobral** [comment]
O cara tem razão!

---

@vi , you have a point!

**Comment by kazzkiq** [comment]
@vi You're right. This repo is focused on creating an open catalog of companies [who are not adhering to data cap](http://www.zdnet.com/article/brazilians-protest-against-fixed-broadband-data-cap/) in Brazil. As its being aimed at Brazilians, it doesn't have a translation, however I think at least a little explanation in english would be interesting to prevent confusion.

cc @jlcarvalho

**Comment by jlcarvalho** [comment]
@vi this is a brazilian project focused on a local issue with internet service providers, i think that there is no need for an English description, since the global community is not the target of this project.

**Comment by vi** [comment]
@jlcarvalho, Somebody may be, for example, investigating situation about ISP around the world for some research. Also there may be people in Brazil who do not know [yet] the language.

**Comment by jlcarvalho** [comment]
@vi, you're right. But I'm afraid that this may confuse people, since not only developers are accessing this repository.

**Comment by jlcarvalho** [comment]
@vi, I'll update the `README.md` with english description soon.

**Comment by robsonsobral** [comment]
@jlcarvalho , a little explanation will cause no harm and can help others. I can't see any trouble on that.

Only one English paragraph is enough.

**Comment by jlcarvalho** [comment]
Done. Soon the automated script will run and the `README.md`will be updated.

cc @robsonsobral, @vi and @kazzkiq

**Comment by jlcarvalho** [comment]
Thanks @vi.
