### ISSUE TITLE
Informar se operadora atende residências, empresas ou ambos

### ISSUE THREAD

**Issue by fbraz3** [InternetSemLimites/InternetSemLimites#33]
Notei que alguns dos provedores cadastrados atendem somente empresas, minha sugestão é algum modo de informarmos isso aos interessados.

**Comment by cuducos** [comment]
Por enquanto tem, no formulário, a parte de “observações”… pode colocar lá
qualquer coisa. Acho que caberia, não?

**Comment by fbraz3** [comment]
Normalmente a solução mais simples é a mais eficaz, ótimo.

**Comment by cuducos** [comment]
Quer acesso ao CMS, aí tu já edita/modera tb?

**Comment by fbraz3** [comment]
Posso auxiliar na moderação sem problemas =)

**Comment by cuducos** [comment]
Como falo contigo em PVT para passar a senha? Telegram ou Twitter, arroba
cuducos, rola?
