### ISSUE TITLE
Contrato Sercomtel prevê SIM limite de franquia

### ISSUE THREAD

**Issue by ozouhades** [InternetSemLimites/InternetSemLimites#43]
Apesar de ter anunciado o contrário no link disponibilizado aqui, A Sercomtel (PR) prevê SIM limites de franquia em seu [contrato](http://prodweb.sercomtel.com.br/sistemas/portalBandaLarga/res/documentos/contrato_supervia.pdf) e nas [descrições dos seus planos](http://prodweb.sercomtel.com.br/sistemas/portalBandaLarga/res/documentos/anexo_ideal.pdf). Tenho tentado sem sucesso obter esclarecimentos da empresa aqui em Londrina, mas enquanto isso penso que seria melhor removê-la da lista, para não correr o risco de incentivar consumidores a migrarem para seus serviços e serem vítimas de um possível golpe.

**Comment by fbraz3** [comment]
É justamente para evitar esse tipo de situação que são aprovados somente provedores com declarações publicas de não limitação, na minha opinião acredito que não seja interessante a retirada do provedor uma vez que há a declaração em questão.

O que acham?

**Comment by cuducos** [comment]
Estou no 3G e não (re)conferi todos os links. Mas por enquanto proponho
adicionar essa fonte como observação e fazermos uma pressão via Facebook e
Twitter para a empresa esclarecer…

**Comment by ozouhades** [comment]
Eu não sou advogado, e não sei o que teria maior valor nesta situação, se a propaganda divulgada ou o contrato assinado. Seria interessante algum advogado ou alguém versado neste tipo de questão legal opinar. Um testemunho apenas: eu já tive minha internet cortada por essa empresa em 2009 justamente por questões relacionadas ao limite de franquia. Obviamente abandonei seus serviços desde então. Se, hoje, eles não pretendem mais aplicar o limite de franquia nem qualquer tipo de redução/corte, por que não removem as cláusulas relativas a isso do contrato? Acho um pouco suspeito, mas repito que um advogado pode nos ajudar a esclarecer tais pontos, assim como nos orientar sobre como podemos nos precaver para que não sejamos vítimas de nenhum eventual golpe.

**Comment by fbraz3** [comment]
Esse golpe seria caracterizado como "propaganda enganosa", o que renderia um belo processo.

**Comment by ozouhades** [comment]
A ideia de pressioná-los é excelente, pois estou fazendo isso sozinho e embora esteja sendo bastante insistente não obtive nenhum resultado. Alguns links para interessados:
- [A página deles no Facebook](https://www.facebook.com/sercomteloficial/)
- [Twitter](https://twitter.com/43sercomtel)
- [Post de divulgação da propaganda no Facebook](https://www.facebook.com/sercomteloficial/photos/a.355064517904441.81285.347620378648855/1004189236325296/?type=3&theater#)
- [Reportagem em jornal local online sobre suposta não-adesão da empresa ao limite de franquia](http://www.bonde.com.br/?id_bonde=1-39--130-20160415)

Continuarei procurando esclarecimentos e usarei esta página para comunicar qualquer avanço.

**Comment by ozouhades** [comment]
Fiz contato com a Sercomtel pelo Facebook ontem, e mais de 24 horas depois não obtive ainda nenhuma resposta. Hoje liguei lá, e como a atendente foi incapaz de sanar minhas dúvidas abri um protocolo de reclamação e ela disse que eles retornarão em até 5 dias úteis.

Embora concorde com a afirmação acima do fbraz3 de que, caso eles imponham sim limites de franquia isso seria passível de um processo por propaganda enganosa, acredito que juridicamente sempre irá prevalecer o que consta no contrato assinado, e por isso proponho que, enquanto a Sercomtel não esclareça o motivo de seu contrato de adesão claramente destoar do que está sendo propagado pelo seu departamento de marketing, no mínimo coloquemos uma nota de observação que chame atenção para esse importante detalhe, conforme o cuducos sugeriu acima. O que acham?

Continuarei insistindo junto à Sercomtel e volto a comentar aqui assim que tenha novidades.

**Comment by cuducos** [comment]
@ozouhades Só esclareça uma coisa para eu ver o que por na nota: no contrato diz que o acesso a internet será _cortado_ ao final da franquia ou terá a _velocidade reduzia_? (Ok, eu poderia ler o contrato linkado, mas você deve saber de cabeça, então resolvi pergunta).

**Comment by cuducos** [comment]
No rodapé do PDF do provedor:

> A título promocional e por tempo indeterminado, a SERCOMTEL não estará aplicando a limitação de franquia disposta no § 6o da Cláusula Segunda do Contrato, podendo voltar a praticá-la com divulgação prévia;

Se é a título _promocional_ voto por tirar a Sercomtel da nossa lista. Alguém se opõe?

**Comment by ozouhades** [comment]
Opa, sem problema @cuducos. Eles falam em redução. Tá aí:
§ 6º O CLIENTE se obriga a utilizar adequadamente o serviço conforme a velocidade contratada, estando ciente que a utilização de tráfego de dados acima da franquia mensal implicará a redução da velocidade contratada para a velocidade estabelecida no Anexo I pela Sercomtel.

**Comment by cuducos** [comment]
Ok… redução é, teoricamente, permitida pelo _Marco Civil da Internet_. Mudo de ideia então, prefiro manter o provedor na lista. Mas, claro!, vou por uma ressalva:

> Previsto em contrato franquia com redução de velocidade, mas sem corte total da conexão.

Muito obrigado por nos alertar sobre isso, @ozouhades ; )

**Comment by robsonsobral** [comment]
Listar provedores com redução de velocidade abre precedente para quase todos, visto os diferentes planos de acesso. Até a Vivo prevê isso em alguns planos novos.

Acho melhor tirar. De desinformação ou quase isso, já temos muita coisa. Me parece um jeito da Sercomtel ganhar publicidade e deixar a porta aberta para mudar de ideia.

**Comment by cuducos** [comment]
@robsonsobral Verdade. Mudei de ideia outra vez.

**Comment by digpixels** [comment]
Vou dar minha opinião tbm, apesar dela ser quase idêntica a do @robsonsobral : eu acho que inserir nesta lista empresas que praticam internet sem franquia apenas com um caráter promocional acaba incentivando empresas a se aproveitar desse momento de pânico causado pela divulgação do limite pelas outras operadoras para lançarem planos "sem limites" e, a qualquer momento, quando a situação se acalmar, acabar com a promoção e prejudicar aqueles que eventualmente possam ter escolhido migrar para essa operadora sem ler direito o contrato.
Acho que sem limites é sem limites, e promoção é promoção.

**Comment by cuducos** [comment]
Já retirei a empresa da lista então, valeu pelo toque e pela discussão ; )

**Comment by ozouhades** [comment]
OK, @cuducos, obrigado. Estava ingenuamente esperando a Sercomtel responder minhas questões via telefone ou Facebook para atualizar a questão aqui, mas parece claro que isso não vai acontecer. Estas empresas precisam entender que de nada adianta fazer propaganda de uma coisa e estabelecer outra em contrato. Eu não tenho nenhum motivo para confiar nesta ou em qualquer outra empresa brasileira do ramo. Quer que confiemos? Remova as cláusulas do contrato. É bem simples.
Obrigado novamente!

**Comment by cuducos** [comment]
A Oi esses dias me disse que atualmente não trabalhava com franquias (deletaram o tuíte depois). Foi exatamente isso que respondi, @ozouhades: https://twitter.com/cuducos/status/724699600691535872 Hahaha…
