### ISSUE TITLE
Legislações e possíveis pedidos de mudança na legislação

### ISSUE THREAD

**Issue by luzfcb** [InternetSemLimites/InternetSemLimites#44]
Ola pessoal, não sei se é relevante, mas seria interessante juntar em um lugar só as informações sobre as legislações pertinentes e possíveis atos que possam resultar na mudança da legislação (para o bem ou para o mal), como esse que está rolando no portal do Senado

https://www12.senado.gov.br/ecidadania/visualizacaoideia?id=49269

**Comment by leomeloxp** [comment]
Valeu @luzfcb acho que seria legal ter sim esse tipo de info agregado para que os usuários pudessem se informar. Vou adicionar sua isso como sugestão no site (front-end) do projeto.

**Comment by leomeloxp** [comment]
Migrada para o repo do front-end: https://github.com/InternetSemLimites/InternetSemLimites.github.io/issues/5
