### ISSUE TITLE
Algar Telecom

### ISSUE THREAD

**Issue by mafhper** [InternetSemLimites/InternetSemLimites#46]
Anunciada como operadora na área do Distrito Federal, a mesma apenas oferece serviço a clientes empresariais.

**Comment by cuducos** [comment]
Tem algum link para validar a info? Se tiver, adiciono como observação. Obrigado.

**Comment by ricardocunha** [comment]
Confirmo a informação do mafhper, não tenho uma info, depois de ver o provedor aqui fiz um questionamento via facebook e eles me retornaram que não está disponível.

**Comment by cuducos** [comment]
Valeu @ricardocunha e @mafhper! Adicionei uma observação lá na Algar. Já já nosso `README.md` é atualizado com isso ; )
