### ISSUE TITLE
Hall of shame offline

### ISSUE THREAD

**Issue by fbraz3** [InternetSemLimites/InternetSemLimites#47]
Está offline o source do hall of shame:

https://internetsemlimites.herokuapp.com/HALL_OF_SHAME.md

**Comment by fbraz3** [comment]
Por ora fiz rollback do arquivo e comentei a cron.

O estranho é que a pagina 404 tem 300B , não deveria passar pela validação do tamanho da página, to vendo isso.

**Comment by fbraz3** [comment]
Falha minha, repositorio desatualizado! =(

**Comment by cuducos** [comment]
Blz! Valeu : )
