### ISSUE TITLE
www.sul.com.br PR e SC

### ISSUE THREAD

**Issue by adrianosb** [InternetSemLimites/InternetSemLimites#48]
www.sul.com.br
PR e SC

**Comment by cuducos** [comment]
@adrianosb, obrigado pela contribuição.

Atualmente o `README.md` (a lista de provedores) é gerado de forma automatizada através do nosso [CMS](https://github.com/InternetSemLimites/PublicAPI), mas você pode cadastrar o provedor no [nosso formulário](https://internetsemlimites.herokuapp.com/new/), ok?

Mas, **antes**, vale ressaltar o que está nesse formulário:

> **URL da fonte da informação**
> 
> Link (redes sociais, nóticia etc.) no qual a empresa se manifestou publicamente afirmando que não irá adotar os limites de franquia.
> 
> Isso é diferente de um link dizendo que ela não adota, hoje, essas medidas. Ou seja, não utilize descrição dos planos ou contratos atuais. Estamos buscando afirmações de compromisso em não adotar franquias no futuro.

Sendo assim, tem alguma manifestação pública da Sul nesse sentido? Ela não ter limites hoje não quer dizer que ela se comprometeu a não adotá-los amanhã.

**Comment by adrianosb** [comment]
Ok, vou buscar a informação se cobrará limite
Em 19/04/2016 13:46, "Eduardo Cuducos" notifications@github.com escreveu:

**Comment by cuducos** [comment]
Ótimo! Muito obrigado mais uma vez, @adrianosb : )
