### ISSUE TITLE
Atualizações das observações para o Rio de Janeiro

### ISSUE THREAD

**Issue by rodrigofitti** [InternetSemLimites/InternetSemLimites#51]
Olá,
Gostaria de contribuir com a alteração dessa observação:
Niitnet     http://archive.is/4qpIZ     Niterói, São Gonçalo, Itaboraí, Magé, Maricá (Itaipuaçú), Rio de Janeiro **(somente empresas da região central)** e Baixada Fluminense

**Comment by cuducos** [comment]
Muito obrigado, @rodrigofitti! Atualizei nosso banco de dados : )
