### ISSUE TITLE
Documentação para registro de nova operadora

### ISSUE THREAD

**Issue by ronniery** [InternetSemLimites/InternetSemLimites#52]
Bom dia senhores, estou construindo um app android com a finalidade de disponibilizar as informações do web server, porém estou também disponibilizando a parte de registro de boas/péssimas operadoras.
1. Existe alguma documentação que eu possa seguir para o cadastro de uma nova operadora? 
2. É possível realizar algum tipo de teste?

**Comment by cuducos** [comment]
Não sei se entendi direito tua pergunta, meu caro… mas vai:
1. Para o nosso projeto usamos esse [modelo](https://github.com/InternetSemLimites/PublicAPI/blob/master/InternetSemLimites/core/models.py#L18) para o cadastro de provedores. Ajuda?
2. Que tipo de testes tens em mente? Para o CMS a API usamos testes [aqui](https://github.com/InternetSemLimites/PublicAPI/tree/master/InternetSemLimites/api/tests), [aqui](https://github.com/InternetSemLimites/PublicAPI/tree/master/InternetSemLimites/core/tests) e [aqui](https://github.com/InternetSemLimites/PublicAPI/tree/master/InternetSemLimites/markdown/tests).

**Comment by ronniery** [comment]
Então, se eu fizer...

Request method: POST

**Comment by ronniery** [comment]
1. Basicamente um json com as informações e um request POST/GET - OK
2. Como inicialmente não consumi sua api de cadastro, eu poderia acabar submetendo informação lixo, exemplo {'name': 'Xpto', 'url': 'http://xp.to', 'coverage': ['GO', 'XC']} não existe estado XC, informações que não iria contribuir em nada, para evitar isto queria saber se existe uma maneira de não enviar informação lixo ao servidor.

Para subir um server local de django/py e complicado? Somente com o que está neste [README.md](https://github.com/InternetSemLimites/PublicAPI#requirements) é o suficiente? Acho que com isto o segundo item se resolve.

**Comment by cuducos** [comment]
This issue was moved to InternetSemLimites/PublicAPI#8
