### ISSUE TITLE
Printscreen da fonte?

### ISSUE THREAD

**Issue by cuducos** [InternetSemLimites/InternetSemLimites#7]
Jean, [a ideia não é minha, mas como o cara aparentemente não tem GitHub](https://www.reddit.com/r/brasil/comments/4em738/lista_colaborativa_de_provedores_que_não_aderirão/d21e4c0), vim sugerir no lugar dele:

> Excelente iniciativa!
> 
> Apenas como sugestão: que tão colocar um print também, junto com a fonte? Posts de Facebook podem ser apagados..

**Comment by jlcarvalho** [comment]
@cuducos, pensei nessa questão dos posts serem apagados mais cedo e realmente o printscreen é uma boa alternativa.

**Comment by anewuser** [comment]
@jlcarvalho  É mais prático e confiável (já que imagens podem ser manipuladas) utilizar o [archive.is](https://archive.is).

**Comment by jlcarvalho** [comment]
@anewuser também é uma ótima ideia.

**Comment by cuducos** [comment]
@anewuser @jlcarvalho Boa. Vou ver se tem API pública, aí automatizo isso de algum jeito.
